Repository transifex/transifex-python, pull requests merged in 2021-06, with the labels that each got.

#53 Get keys from both source and translation (t-tag)
  transifex/native/django/templatetags/transifex.py
Labels: auto-merge

#56 Release: 0.6.0
  tests/native/core/test_core.py
  transifex/native/cds.py
  transifex/native/core.py
Labels: auto-merge, v:0.6.0

#57 Support Django 2 & 3
  .github/workflows/ci.yml
  Makefile
  tests/native/django/test_commands/__init__.py
  tests/native/django/test_commands/test_invalidatetransifex.py
  tests/native/django/test_commands/test_migratetransifex.py
  tests/native/django/test_commands/test_pushtransifex.py
  transifex/native/django/compat.py
  transifex/native/django/management/commands/transifex.py
  transifex/native/django/management/utils/invalidate.py
  transifex/native/django/management/utils/migrate.py
  transifex/native/django/management/utils/push.py
  transifex/native/django/templatetags/transifex.py
  transifex/native/django/tools/migrations/templatetags.py
  transifex/native/django/utils/templates.py
Labels: auto-merge

#58 Release: 0.7.0
  .github/workflows/ci.yml
  Makefile
  tests/native/django/test_commands/__init__.py
  tests/native/django/test_commands/test_invalidatetransifex.py
  tests/native/django/test_commands/test_migratetransifex.py
  tests/native/django/test_commands/test_pushtransifex.py
  transifex/native/django/compat.py
  transifex/native/django/management/commands/transifex.py
  transifex/native/django/management/utils/invalidate.py
  transifex/native/django/management/utils/migrate.py
  transifex/native/django/management/utils/push.py
  transifex/native/django/templatetags/transifex.py
  transifex/native/django/tools/migrations/templatetags.py
  transifex/native/django/utils/templates.py
Labels: auto-merge, v:0.7.0
